services:
  spring-consumer:
    environment:
      - SPRING_KAFKA_TEMPLATE_DEFAULTTOPIC=spring-stream-out

  spring-producer:
    environment:
      - SPRING_KAFKA_TEMPLATE_DEFAULTTOPIC=spring-stream-in

  spring-streams:
    image: spring-streams:1.0.0-SNAPSHOT
    network_mode: host
