app:
  topic: ${TOPIC}

spring:
  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      group-id: ${GROUP_ID}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
